# Generated by Django 3.2.5 on 2021-07-28 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOMERmANAGEMENT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=200)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=200)),
                ('Description', models.TextField()),
                ('Date_Created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
