# Generated by Django 3.2.5 on 2021-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOMERmANAGEMENT', '0002_auto_20210728_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
